{% set name = "slack-bolt" %}
{% set version = "1.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slack_bolt-{{ version }}.tar.gz
  sha256: 694f84a81ba1c4c428ba7daa01d599d3e9fba7a54ad10c11008aa22573b23ff0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pytest-runner ==5.2
    - pip
  run:
    - python >=3.6
    - slack-sdk <4,>=3.21.2

test:
  imports:
    - slack_bolt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/slackapi/bolt-python
  summary: The Bolt Framework for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mbiette
